/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuthError = { 'userNotFound' : null } |
  { 'phoneTaken' : null } |
  { 'invalidCredentials' : null };
export interface LoginRequest { 'password' : string, 'phone' : Phone }
export type Phone = string;
export interface RegisterRequest {
  'pin' : string,
  'password' : string,
  'name' : string,
  'phone' : Phone,
}
export type Result = { 'ok' : Transaction } |
  { 'err' : TxError };
export type Result_1 = { 'ok' : UserPublic } |
  { 'err' : AuthError };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export interface SendMoneyRequest {
  'pin' : string,
  'receiverIdentifier' : string,
  'amount' : bigint,
  'senderId' : UserId,
}
export type Timestamp = bigint;
export interface Transaction {
  'status' : string,
  'txId' : string,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'amount' : bigint,
  'senderId' : UserId,
}
export type TxError = { 'insufficientBalance' : null } |
  { 'selfTransfer' : null } |
  { 'invalidPin' : null } |
  { 'senderNotFound' : null } |
  { 'invalidAmount' : null } |
  { 'receiverNotFound' : null };
export type UserId = string;
export interface UserPublic {
  'balance' : bigint,
  'userId' : UserId,
  'name' : string,
  'phone' : Phone,
}
export interface _SERVICE {
  'applyInterest' : ActorMethod<[UserId], Result_2>,
  'getBalance' : ActorMethod<[UserId], [] | [bigint]>,
  'getTransactions' : ActorMethod<[UserId], Array<Transaction>>,
  'getUser' : ActorMethod<[string], [] | [UserPublic]>,
  'login' : ActorMethod<[LoginRequest], Result_1>,
  'register' : ActorMethod<[RegisterRequest], Result_1>,
  'sendMoney' : ActorMethod<[SendMoneyRequest], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];