/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'status' : IDL.Text,
  'txId' : IDL.Text,
  'receiverId' : UserId,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
  'senderId' : UserId,
});
export const Phone = IDL.Text;
export const UserPublic = IDL.Record({
  'balance' : IDL.Nat,
  'userId' : UserId,
  'name' : IDL.Text,
  'phone' : Phone,
});
export const LoginRequest = IDL.Record({
  'password' : IDL.Text,
  'phone' : Phone,
});
export const AuthError = IDL.Variant({
  'userNotFound' : IDL.Null,
  'phoneTaken' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : UserPublic, 'err' : AuthError });
export const RegisterRequest = IDL.Record({
  'pin' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'phone' : Phone,
});
export const SendMoneyRequest = IDL.Record({
  'pin' : IDL.Text,
  'receiverIdentifier' : IDL.Text,
  'amount' : IDL.Nat,
  'senderId' : UserId,
});
export const TxError = IDL.Variant({
  'insufficientBalance' : IDL.Null,
  'selfTransfer' : IDL.Null,
  'invalidPin' : IDL.Null,
  'senderNotFound' : IDL.Null,
  'invalidAmount' : IDL.Null,
  'receiverNotFound' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : Transaction, 'err' : TxError });

export const idlService = IDL.Service({
  'applyInterest' : IDL.Func([UserId], [Result_2], []),
  'getBalance' : IDL.Func([UserId], [IDL.Opt(IDL.Nat)], ['query']),
  'getTransactions' : IDL.Func([UserId], [IDL.Vec(Transaction)], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'login' : IDL.Func([LoginRequest], [Result_1], []),
  'register' : IDL.Func([RegisterRequest], [Result_1], []),
  'sendMoney' : IDL.Func([SendMoneyRequest], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'status' : IDL.Text,
    'txId' : IDL.Text,
    'receiverId' : UserId,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
    'senderId' : UserId,
  });
  const Phone = IDL.Text;
  const UserPublic = IDL.Record({
    'balance' : IDL.Nat,
    'userId' : UserId,
    'name' : IDL.Text,
    'phone' : Phone,
  });
  const LoginRequest = IDL.Record({ 'password' : IDL.Text, 'phone' : Phone });
  const AuthError = IDL.Variant({
    'userNotFound' : IDL.Null,
    'phoneTaken' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : UserPublic, 'err' : AuthError });
  const RegisterRequest = IDL.Record({
    'pin' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'phone' : Phone,
  });
  const SendMoneyRequest = IDL.Record({
    'pin' : IDL.Text,
    'receiverIdentifier' : IDL.Text,
    'amount' : IDL.Nat,
    'senderId' : UserId,
  });
  const TxError = IDL.Variant({
    'insufficientBalance' : IDL.Null,
    'selfTransfer' : IDL.Null,
    'invalidPin' : IDL.Null,
    'senderNotFound' : IDL.Null,
    'invalidAmount' : IDL.Null,
    'receiverNotFound' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : Transaction, 'err' : TxError });
  
  return IDL.Service({
    'applyInterest' : IDL.Func([UserId], [Result_2], []),
    'getBalance' : IDL.Func([UserId], [IDL.Opt(IDL.Nat)], ['query']),
    'getTransactions' : IDL.Func([UserId], [IDL.Vec(Transaction)], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'login' : IDL.Func([LoginRequest], [Result_1], []),
    'register' : IDL.Func([RegisterRequest], [Result_1], []),
    'sendMoney' : IDL.Func([SendMoneyRequest], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };