/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Timestamp = bigint;
export interface SendMoneyRequest {
    pin: string;
    receiverIdentifier: string;
    amount: bigint;
    senderId: UserId;
}
export interface UserPublic {
    balance: bigint;
    userId: UserId;
    name: string;
    phone: Phone;
}
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result = {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: TxError;
};
export interface RegisterRequest {
    pin: string;
    password: string;
    name: string;
    phone: Phone;
}
export type Phone = string;
export interface LoginRequest {
    password: string;
    phone: Phone;
}
export type Result_1 = {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: AuthError;
};
export interface Transaction {
    status: string;
    txId: string;
    receiverId: UserId;
    timestamp: Timestamp;
    amount: bigint;
    senderId: UserId;
}
export enum AuthError {
    userNotFound = "userNotFound",
    phoneTaken = "phoneTaken",
    invalidCredentials = "invalidCredentials"
}
export enum TxError {
    insufficientBalance = "insufficientBalance",
    selfTransfer = "selfTransfer",
    invalidPin = "invalidPin",
    senderNotFound = "senderNotFound",
    invalidAmount = "invalidAmount",
    receiverNotFound = "receiverNotFound"
}
export interface backendInterface {
    applyInterest(userId: UserId): Promise<Result_2>;
    getBalance(userId: UserId): Promise<bigint | null>;
    getTransactions(userId: UserId): Promise<Array<Transaction>>;
    getUser(identifier: string): Promise<UserPublic | null>;
    login(req: LoginRequest): Promise<Result_1>;
    register(req: RegisterRequest): Promise<Result_1>;
    sendMoney(req: SendMoneyRequest): Promise<Result>;
}
import type { AuthError as _AuthError, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Transaction as _Transaction, TxError as _TxError, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyInterest(arg0: UserId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.applyInterest(arg0);
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyInterest(arg0);
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: UserId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: UserId): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return result;
        }
    }
    async getUser(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: LoginRequest): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterRequest): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMoney(arg0: SendMoneyRequest): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMoney(arg0);
                return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMoney(arg0);
            return from_candid_Result_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthError_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TxError_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxError): TxError {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transaction;
} | {
    err: _TxError;
}): {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: TxError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_TxError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insufficientBalance: null;
} | {
    selfTransfer: null;
} | {
    invalidPin: null;
} | {
    senderNotFound: null;
} | {
    invalidAmount: null;
} | {
    receiverNotFound: null;
}): TxError {
    return "insufficientBalance" in value ? TxError.insufficientBalance : "selfTransfer" in value ? TxError.selfTransfer : "invalidPin" in value ? TxError.invalidPin : "senderNotFound" in value ? TxError.senderNotFound : "invalidAmount" in value ? TxError.invalidAmount : "receiverNotFound" in value ? TxError.receiverNotFound : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userNotFound: null;
} | {
    phoneTaken: null;
} | {
    invalidCredentials: null;
}): AuthError {
    return "userNotFound" in value ? AuthError.userNotFound : "phoneTaken" in value ? AuthError.phoneTaken : "invalidCredentials" in value ? AuthError.invalidCredentials : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
